Class {
	#name : #DivagerMagicTransition,
	#superclass : #Object,
	#category : #Divager
}

{ #category : #'instance creation' }
DivagerMagicTransition class >> on: aBlockClosure [ 
	self shouldBeImplemented.
]

{ #category : #accessing }
DivagerMagicTransition >> magicBlock: aBlockClosure [ 
	self shouldBeImplemented.
]

{ #category : #transition }
DivagerMagicTransition >> transitionTo: anInteger in: aDivagerPaginatedPanePresenter [ 
	self shouldBeImplemented.
]
